### ISSUE TITLE
Update to 2.0 [Tracker]

### ISSUE THREAD

**Issue by jordy25519** [plugblockchain/plug-blockchain#134]
Substrate 2.0 is ~close~ here
It is a good chance to update larger components of this codebase now that the development cadence is slower upstream and hopefully more commitment to API stability.

In general the plug runtime has diverged from substrate and it does not need to follow the runtime changes upstream as they're mostly fed by different network or business requirements.
We do however want to follow the core framework where possible:

Things to pull in (in order of least difficulty):
- [ ] [atomic transcations](https://github.com/paritytech/substrate/pull/6269)

- [ ] [benchmark based weights](https://github.com/paritytech/substrate/issues/6168)
we'd need to update to the new weight system + update benchmarking code

- [ ] consensus (babe + grandpa)
Update to the latest

Take everything in `client/` metric reporting, db backend updates, refactors the lot
- [ ] [general client/ update]

It's not clear if this change was backwards compatible.
e.g. new message types added, will need some careful testing to support current networks.
- [ ] [networking/lib-p2p update]

**Comment by jordy25519** [comment]
Turns out it's much easier to rebuild modules on the new version.
The upgrade is also backwards compatible for existing clients/networks.
