### ISSUE TITLE
[Tracker] 2.0 release

### ISSUE THREAD

**Issue by jordy25519** [plugblockchain/plug-blockchain#153]
The spike/2.0 branch is basically ready, still needs:

TODO:
- [ ] update prml/validator-manager
- [ ] update prml/consortium-permission
- [ ] update wiki/docs including doughnut architecture + Option signed extension type

**Comment by jordy25519** [comment]
Update to upstream 3.0: https://github.com/paritytech/substrate/pull/8098
