### ISSUE TITLE
[Tracker] 3.0 release

### ISSUE THREAD

**Issue by jordy25519** [plugblockchain/plug-blockchain#196]
Generic Asset
- [x] GA provide account store #181
- [x] existential deposit rules #183
- [x] fix cumulative lock behvaiour #193 
- [x] existential deposit rules #183
- [ ] re-entrancy checks #188 

Transaction Payment RPC
- [x] Restore previous behaviour #180
